name: axe-core/cli a11y Audit
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  axe-core-cli-a11y-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd axe-core-cli-demo && npm ci
    - name: Install Chrome browser
      run: cd axe-playwright-e2e-demo && npx browser-driver-manager install chrome
    - name: Run axe-core-cli a11y tests
      run: cd axe-playwright-e2e-demo && npm run audit
